#!/bin/bash


# ------ +
# Inputs, Outputs, Args etc
# ----------------- +

# Take a string input in var $N
read -p "Enter the hostname for the new virtual host: " N

# Take a single char Y/N input
read -p "Setup a local SSL? (y/n) " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
  echo "It's a Yes"
fi


# ------ +
# Variables
# ----------------- +

# Check if a var is empty
if [ -z "$P" ]; then
  echo "It's Empty"
fi

# Arithimetic

let X=1+2
echo $X // 3
let Y=$X+3
echo $Y // 6

# ------ +
# Conditions, Regex Patterns etc
# ----------------- +

NUMERIC='^[0-9]+$'

# If a pattern matches
if [[ $N =~ $NUMERIC ]] ; then
  echo "Matches"
fi

# Compare numeric value of a var
if (( $SSL == 1 )); then
  echo "Matches"
 fi

# ------ +
# Text Formatting
# ----------------- +

BOLD=$(tput bold)
NORMAL=$(tput sgr0)
RED='\x1b[31m'
YELLOW='\x1b[33m'
NONE='\033[00m'

# ------ +
# Find and Replace
# ----------------- +

# Replace a text with text
sed -i "s|find this|replace with this|g" /in/this/file

# Replace entire line matching a string pattern
sed -i "/find this/c\replace entire line with this line" /in/this/file

# ------ +
# Files and Directories 
# ----------------- +

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# If a file exists
if [ -f /path/to/file ]; then
  echo "Exits"
fi


# ------ +
# Windows, Desktop, Workspaces
# ----------------- +

CURRENT_WORKSPACE=$(wmctrl -d | grep \* | cut -d' ' -f1)+1
