#!/bin/bash

# ------ +
# Variables
# ----------------- +

# Arithimetic

let X=1+2
echo $X // 3
let Y=$X+3
echo $Y // 6

# ------ +
# Regex Patterns
# ----------------- +

NUMERIC='^[0-9]+$'

# If a pattern matches
if [[ $N =~ $NUMERIC ]] ; then
  echo "Matches"
fi

# ------ +
# Text Formatting
# ----------------- +

BOLD=$(tput bold)
NORMAL=$(tput sgr0)

# ------ +
# Find and Replace
# ----------------- +

# Replace a text with text
sed -i "s|findthis|replacewiththis|g" /in/this/file

# Replace entire line matching a string pattern
sed -i "/find this/c\replace with this entire line" /in/this/file

# ------ +
# Files and Directories 
# ----------------- +

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# If a file exists
if [ -f /path/to/file ]; then
  echo "Exits"
fi


# ------ +
# Windows, Desktop, Workspaces
# ----------------- +

CURRENT_WORKSPACE=$(wmctrl -d | grep \* | cut -d' ' -f1)+1
